name: native_color_picker
description: Picking a color natively on each platform.
version: 2.0.0
homepage: https://github.com/rodydavis/native_color_picker

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
